apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-squares
spec:
  selector:
    matchLabels:
      app: infinite-squares
  replicas: 1
  template:
    metadata:
      labels:
        app: infinite-squares
    spec:
      containers:
      - name: infinite-squares
        image: siddharth67/infinite-shapes:squares
