apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-circle
spec:
  selector:
    matchLabels:
      app: infinite-circle
  replicas: 1
  template:
    metadata:
      labels:
        app: infinite-circle
    spec:
      containers:
      - name: infinite-circle
        image: siddharth67/infinite-shapes:circle
